package com.talkweb.ylimaf.web.pojo;

public class Dict {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.DICT_ID
     *
     * @mbggenerated
     */
    private String dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict.DICT_DESC
     *
     * @mbggenerated
     */
    private String dictDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.ID
     *
     * @return the value of dict.ID
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.ID
     *
     * @param id the value for dict.ID
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.DICT_ID
     *
     * @return the value of dict.DICT_ID
     * @mbggenerated
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.DICT_ID
     *
     * @param dictId the value for dict.DICT_ID
     * @mbggenerated
     */
    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict.DICT_DESC
     *
     * @return the value of dict.DICT_DESC
     * @mbggenerated
     */
    public String getDictDesc() {
        return dictDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict.DICT_DESC
     *
     * @param dictDesc the value for dict.DICT_DESC
     * @mbggenerated
     */
    public void setDictDesc(String dictDesc) {
        this.dictDesc = dictDesc == null ? null : dictDesc.trim();
    }
}