package com.talkweb.ylimaf.web.pojo;

import com.zaxk.study.mybatis.Page;

import java.util.ArrayList;
import java.util.List;

public class DictItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    protected Page page;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public DictItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public Page getPage() {
        return page;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public void setPage(Page page) {
        this.page = page;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNull() {
            addCriterion("DICT_ID is null");
            return (Criteria) this;
        }

        public Criteria andDictIdIsNotNull() {
            addCriterion("DICT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDictIdEqualTo(String value) {
            addCriterion("DICT_ID =", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotEqualTo(String value) {
            addCriterion("DICT_ID <>", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThan(String value) {
            addCriterion("DICT_ID >", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdGreaterThanOrEqualTo(String value) {
            addCriterion("DICT_ID >=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThan(String value) {
            addCriterion("DICT_ID <", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLessThanOrEqualTo(String value) {
            addCriterion("DICT_ID <=", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdLike(String value) {
            addCriterion("DICT_ID like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotLike(String value) {
            addCriterion("DICT_ID not like", value, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdIn(List<String> values) {
            addCriterion("DICT_ID in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotIn(List<String> values) {
            addCriterion("DICT_ID not in", values, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdBetween(String value1, String value2) {
            addCriterion("DICT_ID between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictIdNotBetween(String value1, String value2) {
            addCriterion("DICT_ID not between", value1, value2, "dictId");
            return (Criteria) this;
        }

        public Criteria andDictItemIsNull() {
            addCriterion("DICT_ITEM is null");
            return (Criteria) this;
        }

        public Criteria andDictItemIsNotNull() {
            addCriterion("DICT_ITEM is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemEqualTo(String value) {
            addCriterion("DICT_ITEM =", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemNotEqualTo(String value) {
            addCriterion("DICT_ITEM <>", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemGreaterThan(String value) {
            addCriterion("DICT_ITEM >", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemGreaterThanOrEqualTo(String value) {
            addCriterion("DICT_ITEM >=", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemLessThan(String value) {
            addCriterion("DICT_ITEM <", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemLessThanOrEqualTo(String value) {
            addCriterion("DICT_ITEM <=", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemLike(String value) {
            addCriterion("DICT_ITEM like", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemNotLike(String value) {
            addCriterion("DICT_ITEM not like", value, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemIn(List<String> values) {
            addCriterion("DICT_ITEM in", values, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemNotIn(List<String> values) {
            addCriterion("DICT_ITEM not in", values, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemBetween(String value1, String value2) {
            addCriterion("DICT_ITEM between", value1, value2, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemNotBetween(String value1, String value2) {
            addCriterion("DICT_ITEM not between", value1, value2, "dictItem");
            return (Criteria) this;
        }

        public Criteria andDictItemValueIsNull() {
            addCriterion("DICT_ITEM_VALUE is null");
            return (Criteria) this;
        }

        public Criteria andDictItemValueIsNotNull() {
            addCriterion("DICT_ITEM_VALUE is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemValueEqualTo(String value) {
            addCriterion("DICT_ITEM_VALUE =", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotEqualTo(String value) {
            addCriterion("DICT_ITEM_VALUE <>", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueGreaterThan(String value) {
            addCriterion("DICT_ITEM_VALUE >", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueGreaterThanOrEqualTo(String value) {
            addCriterion("DICT_ITEM_VALUE >=", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueLessThan(String value) {
            addCriterion("DICT_ITEM_VALUE <", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueLessThanOrEqualTo(String value) {
            addCriterion("DICT_ITEM_VALUE <=", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueLike(String value) {
            addCriterion("DICT_ITEM_VALUE like", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotLike(String value) {
            addCriterion("DICT_ITEM_VALUE not like", value, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueIn(List<String> values) {
            addCriterion("DICT_ITEM_VALUE in", values, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotIn(List<String> values) {
            addCriterion("DICT_ITEM_VALUE not in", values, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueBetween(String value1, String value2) {
            addCriterion("DICT_ITEM_VALUE between", value1, value2, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemValueNotBetween(String value1, String value2) {
            addCriterion("DICT_ITEM_VALUE not between", value1, value2, "dictItemValue");
            return (Criteria) this;
        }

        public Criteria andDictItemDescIsNull() {
            addCriterion("DICT_ITEM_DESC is null");
            return (Criteria) this;
        }

        public Criteria andDictItemDescIsNotNull() {
            addCriterion("DICT_ITEM_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andDictItemDescEqualTo(String value) {
            addCriterion("DICT_ITEM_DESC =", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescNotEqualTo(String value) {
            addCriterion("DICT_ITEM_DESC <>", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescGreaterThan(String value) {
            addCriterion("DICT_ITEM_DESC >", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescGreaterThanOrEqualTo(String value) {
            addCriterion("DICT_ITEM_DESC >=", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescLessThan(String value) {
            addCriterion("DICT_ITEM_DESC <", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescLessThanOrEqualTo(String value) {
            addCriterion("DICT_ITEM_DESC <=", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescLike(String value) {
            addCriterion("DICT_ITEM_DESC like", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescNotLike(String value) {
            addCriterion("DICT_ITEM_DESC not like", value, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescIn(List<String> values) {
            addCriterion("DICT_ITEM_DESC in", values, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescNotIn(List<String> values) {
            addCriterion("DICT_ITEM_DESC not in", values, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescBetween(String value1, String value2) {
            addCriterion("DICT_ITEM_DESC between", value1, value2, "dictItemDesc");
            return (Criteria) this;
        }

        public Criteria andDictItemDescNotBetween(String value1, String value2) {
            addCriterion("DICT_ITEM_DESC not between", value1, value2, "dictItemDesc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_item
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}