package com.talkweb.ylimaf.web.pojo;

public class DictItem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.ID
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.DICT_ID
     *
     * @mbggenerated
     */
    private String dictId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.DICT_ITEM
     *
     * @mbggenerated
     */
    private String dictItem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.DICT_ITEM_VALUE
     *
     * @mbggenerated
     */
    private String dictItemValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dict_item.DICT_ITEM_DESC
     *
     * @mbggenerated
     */
    private String dictItemDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.ID
     *
     * @return the value of dict_item.ID
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.ID
     *
     * @param id the value for dict_item.ID
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.DICT_ID
     *
     * @return the value of dict_item.DICT_ID
     *
     * @mbggenerated
     */
    public String getDictId() {
        return dictId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.DICT_ID
     *
     * @param dictId the value for dict_item.DICT_ID
     *
     * @mbggenerated
     */
    public void setDictId(String dictId) {
        this.dictId = dictId == null ? null : dictId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.DICT_ITEM
     *
     * @return the value of dict_item.DICT_ITEM
     *
     * @mbggenerated
     */
    public String getDictItem() {
        return dictItem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.DICT_ITEM
     *
     * @param dictItem the value for dict_item.DICT_ITEM
     *
     * @mbggenerated
     */
    public void setDictItem(String dictItem) {
        this.dictItem = dictItem == null ? null : dictItem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.DICT_ITEM_VALUE
     *
     * @return the value of dict_item.DICT_ITEM_VALUE
     *
     * @mbggenerated
     */
    public String getDictItemValue() {
        return dictItemValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.DICT_ITEM_VALUE
     *
     * @param dictItemValue the value for dict_item.DICT_ITEM_VALUE
     *
     * @mbggenerated
     */
    public void setDictItemValue(String dictItemValue) {
        this.dictItemValue = dictItemValue == null ? null : dictItemValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dict_item.DICT_ITEM_DESC
     *
     * @return the value of dict_item.DICT_ITEM_DESC
     * @mbggenerated
     */
    public String getDictItemDesc() {
        return dictItemDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dict_item.DICT_ITEM_DESC
     *
     * @param dictItemDesc the value for dict_item.DICT_ITEM_DESC
     * @mbggenerated
     */
    public void setDictItemDesc(String dictItemDesc) {
        this.dictItemDesc = dictItemDesc == null ? null : dictItemDesc.trim();
    }
}