package com.talkweb.ylimaf.web.dao;

import com.talkweb.ylimaf.web.pojo.DictItem;
import com.talkweb.ylimaf.web.pojo.DictItemExample;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
@Cacheable(value = "eternalCache")
public interface DictItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int insert(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int insertSelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    List<DictItem> selectByExample(DictItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    DictItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DictItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DictItem record);
}